apiVersion: v1
kind: Pod
metadata:
  name: dnstools
  namespace: default
spec:
  containers:
  - name: dnstools
    image: infoblox/dnstools
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always